services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./:/usr/src/api               # Monta código-fonte local
      - /usr/src/api/node_modules     # Isola node_modules dentro do container
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
      # ? Força polling para detectar mudanças de arquivo
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: 100
    ports:
      - "8080:3000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "35000:5432"
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data     
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    restart: always