# Dockerfile.dev
FROM node:24.0.0-slim

WORKDIR /usr/src/api

# 1) instala deps e aplica chown para o usuário node
COPY package*.json ./
RUN npm install \
 && chown -R node:node /usr/src/api

# 2) global tools
RUN npm install -g @nestjs/cli nodemon ts-node typescript tsconfig-paths

# 3) copia o restante do código e garante permissão
COPY . .

RUN chown -R node:node /usr/src/api

USER node

EXPOSE 3000

CMD [ "nodemon", "--watch", "src", "--ext", "ts", "--exec", "ts-node -r tsconfig-paths/register src/main.ts" ]