### list orders

GET http://localhost:8080/orders

### get orders

GET http://localhost:8080/orders/dev_Ol0AoRTs063v49BEJESy2

### create orders

POST http://localhost:8080/orders/
Content-Type: application/json

{
    "clientId": "3d6d9cbd-f09c-49f8-89e1-eb10ab26254f",
    "items": "Torsilax",
    "total": 100
}

### update orders

PATCH http://localhost:8080/orders/22d108e9-5c99-4367-a58a-9e62fd85fa84
Content-Type: application/json

{
    "status": "cancelado"
}

### delete orders
DELETE http://localhost:8080/orders/a68ce368-fa31-465f-b97d-0114e849281f