### list orders

GET http://localhost:8080/orders

### get orders

GET http://localhost:8080/orders/d613525c-575c-436c-8352-1491a76a1b20

### create orders

POST http://localhost:8080/orders/
Content-Type: application/json

{
    "clientId": "98e4efb1-1323-44b6-9116-d5cbc55007d8",
    "items": "Dorflex",
    "total": 30
}

### update orders

PATCH http://localhost:8080/orders/d613525c-575c-436c-8352-1491a76a1b20
Content-Type: application/json

{
    "status": "cancelado"
}

### delete orders
DELETE http://localhost:8080/orders/a68ce368-fa31-465f-b97d-0114e849281f