### list customers

GET http://localhost:8080/customers

### get customers

GET http://localhost:8080/customers/98e4efb1-1323-44b6-9116-d5cbc55007d8

### create customers

POST http://localhost:8080/customers/
Content-Type: application/json

{
    "name": "Drogaria Francisco"
}

### update customers

PATCH http://localhost:8080/customers/98e4efb1-1323-44b6-9116-d5cbc55007d8
Content-Type: application/json

{
    "name": "Drogaria Santo Bento"
}
### delete customers

DELETE http://localhost:8080/customers/52cfea2d-88fb-4e10-86a8-1b0070ac1ead