### list stripe

GET http://localhost:8080/stripe

### get stripe

# GET http://localhost:8080/stripe/22d108e9-5c99-4367-a58a-9e62fd85fa84

### create stripe

POST http://localhost:8080/stripe/
Content-Type: application/json

{
  "amount": 100,
  "currency": "brl",
  "metadata": {
    "orderId": "22d108e9-5c99-4367-a58a-9e62fd85fa84"
  }
}

### update stripe

# PATCH http://localhost:8080/stripe/22d108e9-5c99-4367-a58a-9e62fd85fa84
# Content-Type: application/json

# {
#     "status": "cancelado"
# }

### delete stripe
# DELETE http://localhost:8080/stripe/a68ce368-fa31-465f-b97d-0114e849281f